### ISSUE TITLE
List all Brightway Dependencies

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-interactive#21]
Adding new packages to a Pyodide kernel involves:

[(JupyterLite) "Use additional Python packages"](https://jupyterlite.readthedocs.io/en/latest/howto/python/packages.html)
[(Pyodide) "Loading packages"](https://pyodide.org/en/stable/usage/loading-packages.html#loading-packages)

For instance,

```
%pip install -q bw2io
```

throws [the error](https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package)

```
ValueError: Can't find a pure Python 3 wheel for 'psutil'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
```

This was briefly discussed in 2022 with the Pyodide team in https://github.com/pyodide/pyodide/issues/3056:

> `psutil` won't be very useful on Pyodide. Emscripten platform does not support any process, resource, signals, or similar POSIX APIs. Browsers are also sandboxed. You won't be able to see or modify any processes on the host system.

A complete list of all dependencies of the Brightway ecosystem must therefore be compiled.

## Tasks

- [x] list all requirements of `bw2io` (and their `pyodide`/`emscripten-forge` status)
- [x] list all requirements of `bw2data` (and their `pyodide`/`emscripten-forge` status)
- [x] list all requirements of `bw2calc` (and their `pyodide`/`emscripten-forge` status)
- [x] list all requirements of `bw2analyzer` (and their `pyodide`/`emscripten-forge` status)

**Comment by michaelweinold** [comment]
| package | required by | [included in pyodide?](https://pyodide.org/en/stable/usage/packages-in-pyodide.html) | can be installed/pure python? | comment |
| -------- | ------------ | -------------------- | ------------------------------ | --------- |
| [lxml](https://lxml.de/) | bw2io | yes | yes | |
| [numpy](https://numpy.org/doc/) | all | yes | yes | |
| [openpyxl](https://openpyxl.readthedocs.io/en/stable/) | bw2io | [no](https://github.com/pyodide/pyodide/issues/2959) | yes  | | 
| [psutil]() | all | [no](https://github.com/pyodide/pyodide/issues/3056) | [no](https://github.com/pyodide/pyodide/issues/3056) | browser is sandboxed | 
| [pyprind](https://github.com/rasbt/pyprind) | no | yes | |

**Comment by michaelweinold** [comment]
## Follow-Up

| package | purpose | comment | 
| -------- | --------- | --------- |
| peewee | database engine (SQL) | none |
